<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Logliy\\phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src', $vendorDir . '/phpdocumentor/reflection-common/src'),
    'Logliy\\Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Logliy\\Webauthn\\' => array($vendorDir . '/web-auth/webauthn-lib/src'),
    'Logliy\\Symfony\\Polyfill\\Uuid\\' => array($vendorDir . '/symfony/polyfill-uuid'),
    'Logliy\\Symfony\\Polyfill\\Php84\\' => array($vendorDir . '/symfony/polyfill-php84'),
    'Logliy\\Symfony\\Polyfill\\Php83\\' => array($vendorDir . '/symfony/polyfill-php83'),
    'Logliy\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Logliy\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Logliy\\Symfony\\Polyfill\\Intl\\Grapheme\\' => array($vendorDir . '/symfony/polyfill-intl-grapheme'),
    'Logliy\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Logliy\\Symfony\\Component\\Uid\\' => array($vendorDir . '/symfony/uid'),
    'Logliy\\Symfony\\Component\\TypeInfo\\' => array($vendorDir . '/symfony/type-info'),
    'Logliy\\Symfony\\Component\\String\\' => array($vendorDir . '/symfony/string'),
    'Logliy\\Symfony\\Component\\Serializer\\' => array($vendorDir . '/symfony/serializer'),
    'Logliy\\Symfony\\Component\\PropertyInfo\\' => array($vendorDir . '/symfony/property-info'),
    'Logliy\\Symfony\\Component\\PropertyAccess\\' => array($vendorDir . '/symfony/property-access'),
    'Logliy\\Symfony\\Component\\Clock\\' => array($vendorDir . '/symfony/clock'),
    'Logliy\\SpomkyLabs\\Pki\\' => array($vendorDir . '/spomky-labs/pki-framework/src'),
    'Logliy\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Logliy\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'Logliy\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Logliy\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Logliy\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'Logliy\\PHPStan\\PhpDocParser\\' => array($vendorDir . '/phpstan/phpdoc-parser/src'),
    'Logliy\\Doctrine\\Deprecations\\' => array($vendorDir . '/doctrine/deprecations/src'),
    'Logliy\\Cose\\' => array($vendorDir . '/web-auth/cose-lib/src'),
    'Logliy\\CBOR\\' => array($vendorDir . '/spomky-labs/cbor-php/src'),
    'Logliy\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
);
